### ISSUE TITLE
非常好用！已经写了114514个脚本了，去掉了1919810个网站的侧边栏，孩子很喜欢

### ISSUE THREAD

**Issue by DearVa** [feast107/DocCleaner#1]
关注原神官方喵，关注原神官方谢谢喵

**Comment by feast107** [comment]
还没 Initial commit 就开始用了事罢

**Comment by DearVa** [comment]
你说得对，但是DocCleaner.user.js是由终宴自主研发的Insider Build版本，在弱类型的js语言中，受脚本关注的控件，会被授予依赖注入，操控布局之力。
